spring:
  application:
    name: demo-prometheus
server:
  port: 8890

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
