version: '3.8'

networks:
  monitoring:

services:
  # 数据可视化展示
  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.9
    ports:
      - "3000:3000"
    networks:
      - monitoring
  # 服务状态收集
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.1
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
