spring:
  rabbitmq:
    # 默认MQ
    addresses: localhost:5672
    username: guest
    password: guest
    # 第二个MQ
    second:
      addresses: 192.168.110.243:5672
      username: guest
      password: guest


