# application-bak.yml (不能是bootstrap.yml)
spring:
  application:
    name: klaus-demo-nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        group: ${spring.profiles.active}
        namespace: klaus
        file-extension: yml
        shared-configs:
          - data-id: common.yml
            group: ${spring.profiles.active}
            refresh: true
      discovery:
        group: ${spring.profiles.active}
        namespace: klaus
  config:
    import:
      - optional:nacos:common.yml